it('open the website', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
})

it('confirm the title of the page is XYZ Bank', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.title().should('eq', 'XYZ Bank')
})

it('click on Customer Login', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
})

it('choose a name from the Your Name drop down', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
})

it('click on Login', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
})

it('confirm the selected name is displayed after Welcome', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('.fontBig').should('contain', 'Harry Potter')
})

it('confirm the currency is Dollar', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('.currency').should('contain', 'Dollar')
})

it('click on Deposit', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
})

it('enter the amount to be deposited', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
})

it('click on Deposit', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
})

it('confirm "Deposit Successful" is displayed', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
})

it('click on Transactions', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
})

it('confirm the amount entered is displayed under Amount column', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(1).should('contain', '100')
})

it('confirm the transaction type is credit', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
})

it('click on Back button', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
})

it('click on Withdrawal', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
  cy.get('button[ng-click="withdrawl()"]').click()
})

it('enter the same amount you deposited', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
  cy.get('button[ng-click="withdrawl()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
})

it('click on Withdraw', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
  cy.get('button[ng-click="withdrawl()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
})

it('confirm "Transaction Successful" is displayed', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
  cy.get('button[ng-click="withdrawl()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Transaction Successful')
})

it('click on Transactions', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
  cy.get('button[ng-click="withdrawl()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Transaction Successful')
  cy.get('button[ng-click="transactions()"]').click()
})

it('confirm there is one more row with Transaction Type is debit', () => {
  cy.visit('https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login')
  cy.get('button[ng-click="customer()"]').click()
  cy.get('#userSelect').select('Harry Potter')
  cy.get('button[type="submit"]').click()
  cy.get('button[ng-click="deposit()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Deposit Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Credit')
  cy.get('button[ng-click="back()"]').click()
  cy.get('button[ng-click="withdrawl()"]').click()
  cy.get('input[ng-model="amount"]').type('100')
  cy.get('button[type="submit"]').click()
  cy.get('.error').should('contain', 'Transaction Successful')
  cy.get('button[ng-click="transactions()"]').click()
  cy.get('tr').last().find('td').eq(2).should('contain', 'Debit')
})